services:
  php:
    build:
      context: .docker/php
    volumes:
      - ./:/var/www/symfony
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    networks:
      - symfony_app
    ports:
      - 80:80
  mysql:
    image: mysql:8.1
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_app:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - symfony_app

volumes:
  symfony_app_var:
  symfony_app_vendor:
  mysql_app:

networks:
  symfony_app: